language: crystal

env:
  global:
    GIT_COMMITTER_NAME: travis-ci
    GIT_COMMITTER_EMAIL: travis@travis-ci.org

script:
- crystal spec
- crystal tool format --check src spec
- "if [ $TRAVIS_TEST_RESULT -eq 0 ]; then scripts/generate-docs.sh && curl https://raw.githubusercontent.com/straight-shoota/autodeploy-docs/master/autodeploy-docs.sh | bash; fi"
